### PR TITLE
API-support for tags

### PR DESCRIPTION
**Pull request by Nuri0**
Complete API-support for getting, creating, changing and deleting tags. Sadly I was unable to get your tests to run on my machine (most certainly due to my inability) so I skipped creating automatic testing for tag.js. I ended up only testing the new feature manually in my own project, but everything seemed to work smoothly.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
This looks great! I'll need to add tests before I can merge it in, but that doesn't look too hard. 

Would you describe for me the problems you were having? Are you able to run the habitrpg repo locally at all?

**Comment by Nuri0** [comment]
No, I'm not able to run habitrpg on my machine as it sadly even fails on `npm install` (due to some bower error I couldn't fix yet). The main reason seems to be, that I'm running an old-windows-machine, where it's very bothersome to get all dependencies ... at least for me.

**Comment by crookedneighbor** [comment]
Merged in with https://github.com/crookedneighbor/habitica-node/commit/755f4d9dbd766ce7289ec4a6ca5931e7bb68ae57

This will count towards a contributor tier for writing third party tools! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.   

I can also add you to the package.json as a contributor. What name and email would you like to have listed there?

**Comment by Nuri0** [comment]
Thanks, that would be great! My User ID is `0e415cf9-f9bb-4f01-bb15-a300c3b2bc00` and you can take my name and email from my github profile.

**Comment by crookedneighbor** [comment]
Tier awarded! You are now a level 1 Comrade (contributor who has worked on a third party tool). You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

I've added you to the contributor's list: https://github.com/crookedneighbor/habitica-node/commit/d07cfbde5bbb5c22f30c8add52f231ec96fb0141

**Pull request closed without merging**
